
services:
  api:
    image: khushbu308/loan-api:latest
    container_name: loan_api
    ports:
      - "8000:8000"

  ui:
    image: khushbu308/loan-prediction-ui:latest
    container_name: loan_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
